<a href="https://colab.research.google.com/github/PIYALI-bhunia/MultimodelDataPreprocessing/blob/main/TfIdf_tobacco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import pathlib

In [3]:
data_root = pathlib.Path('/content/drive/MyDrive/tobaco_OCR/')

for item in data_root.iterdir():
  print(item)

/content/drive/MyDrive/tobaco_OCR/Scientific
/content/drive/MyDrive/tobaco_OCR/Resume
/content/drive/MyDrive/tobaco_OCR/Report
/content/drive/MyDrive/tobaco_OCR/Note
/content/drive/MyDrive/tobaco_OCR/Memo
/content/drive/MyDrive/tobaco_OCR/News
/content/drive/MyDrive/tobaco_OCR/Letter
/content/drive/MyDrive/tobaco_OCR/Form
/content/drive/MyDrive/tobaco_OCR/Email
/content/drive/MyDrive/tobaco_OCR/ADVE


In [4]:
def get_file_paths_and_labels(data_root):
     text_paths = [str(path) for path in data_root.glob('*/*.txt')]
     labels = [p.split("/")[-2] for p in text_paths]
     return text_paths, labels

text_paths, labels = get_file_paths_and_labels(data_root)
print(len(text_paths))
print(labels)


3482
['Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 'Scientific', 

In [5]:
texts = []
for this_text in text_paths:
    with open(this_text) as f:
        lines = f.readlines()
        lines  = ' '.join(lines)
        texts.append(lines)
        

print(len(texts))

3482


In [7]:
df = pd.DataFrame(list(zip(text_paths, texts,labels)),
               columns =['path', 'text','our_label'])
df

path  \
0     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
1     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
2     /content/drive/MyDrive/tobaco_OCR/Scientific/P...   
3     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
4     /content/drive/MyDrive/tobaco_OCR/Scientific/1...   
...                                                 ...   
3477  /content/drive/MyDrive/tobaco_OCR/ADVE/2064932...   
3478  /content/drive/MyDrive/tobaco_OCR/ADVE/2070715...   
3479  /content/drive/MyDrive/tobaco_OCR/ADVE/2061000...   
3480  /content/drive/MyDrive/tobaco_OCR/ADVE/2084426...   
3481  /content/drive/MyDrive/tobaco_OCR/ADVE/5127256...   

                                                   text   our_label  
0     PROJECT TITLE: Project Tomorrow CON F{ 0 EN I ...  Scientific  
1     PAGE 0\n De. W. Fink\n Vice Director Research\...  Scientific  
2     Bf). yas- 737 fet /970\n Cre part)\n THE VETER...  Scientific  
3     Measurement of the Sampling Efficiency of ‘Cur...  Scientific  
4     H\n a\n —_ #\n 786\n New Scientest 29 Septerob...  Scientific  
...                                                 ...         ...  
3477  as\n Kent Golden Lights Menthol #107\n People ...        ADVE  
3478  Dare to be More:\n a\n ta\n © 1986 (11R.J. REY...        ADVE  
3479                                      \n 2061000301        ADVE  
3480  \n \n \n \n eS\n MARIBORO L #835\n COUNTRY WEE...        ADVE  
3481                                                           ADVE  

[3482 rows x 3 columns]

In [8]:
import re
df['text'] = [re.sub(r'[^\w\s]','',s) for s in df['text']]
df['text']  = [s.replace('\n','') for s in df['text']]
df

path  \
0     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
1     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
2     /content/drive/MyDrive/tobaco_OCR/Scientific/P...   
3     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
4     /content/drive/MyDrive/tobaco_OCR/Scientific/1...   
...                                                 ...   
3477  /content/drive/MyDrive/tobaco_OCR/ADVE/2064932...   
3478  /content/drive/MyDrive/tobaco_OCR/ADVE/2070715...   
3479  /content/drive/MyDrive/tobaco_OCR/ADVE/2061000...   
3480  /content/drive/MyDrive/tobaco_OCR/ADVE/2084426...   
3481  /content/drive/MyDrive/tobaco_OCR/ADVE/5127256...   

                                                   text   our_label  
0     PROJECT TITLE Project Tomorrow CON F 0 EN I AL...  Scientific  
1     PAGE 0 De W Fink Vice Director Research Fabriq...  Scientific  
2     Bf yas 737 fet 970 Cre part THE VETERANS ADMIN...  Scientific  
3     Measurement of the Sampling Efficiency of Curr...  Scientific  
4     H a _  786 New Scientest 29 Septerober 1977   ...  Scientific  
...                                                 ...         ...  
3477  as Kent Golden Lights Menthol 107 People 1978 ...        ADVE  
3478  Dare to be More a ta  1986 11RJ REYNOLDS TOBAC...        ADVE  
3479                                         2061000301        ADVE  
3480      eS MARIBORO L 835 COUNTRY WEEKLY 2800     ...        ADVE  
3481                                                           ADVE  

[3482 rows x 3 columns]

# Spacy word Preprocessing

In [9]:
## Tokenize, Lemmatize, stopwords removal
import spacy 
import nltk
nlp = spacy.load("en", disable=['parser', 'tagger', 'ner'])
from nltk.corpus import stopwords
nltk.download('stopwords')
stops = stopwords.words("english")

def normalize(comment, lowercase, remove_stopwords):
    if lowercase:
        comment = comment.lower()
    comment = nlp(comment)
    lemmatized = list()
    for word in comment:
        lemma = word.lemma_.strip()
        if lemma:
            if not remove_stopwords or (remove_stopwords and lemma not in stops):
                lemmatized.append(lemma)
    return " ".join(lemmatized)


df['text'] = df['text'].apply(normalize, lowercase=True, remove_stopwords=True)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [10]:
df

path  \
0     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
1     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
2     /content/drive/MyDrive/tobaco_OCR/Scientific/P...   
3     /content/drive/MyDrive/tobaco_OCR/Scientific/2...   
4     /content/drive/MyDrive/tobaco_OCR/Scientific/1...   
...                                                 ...   
3477  /content/drive/MyDrive/tobaco_OCR/ADVE/2064932...   
3478  /content/drive/MyDrive/tobaco_OCR/ADVE/2070715...   
3479  /content/drive/MyDrive/tobaco_OCR/ADVE/2061000...   
3480  /content/drive/MyDrive/tobaco_OCR/ADVE/2084426...   
3481  /content/drive/MyDrive/tobaco_OCR/ADVE/5127256...   

                                                   text   our_label  
0     project title project tomorrow con f 0 en al p...  Scientific  
1     page 0 de w fink vice director research fabriq...  Scientific  
2     bf yas 737 fet 970 cre part veteran administra...  Scientific  
3     measurement sample efficiency currently availa...  Scientific  
4     h _ 786 new scientest 29 septerober 1977 oe ge...  Scientific  
...                                                 ...         ...  
3477  kent golden light menthol 107 people 1978 ah y...        ADVE  
3478  dare much ta 1986 11rj reynolds tobacco co 665...        ADVE  
3479                                         2061000301        ADVE  
3480  es mariboro l 835 country weekly 2800 te 8 2a ...        ADVE  
3481                                                           ADVE  

[3482 rows x 3 columns]

# Tf_Idf

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(df['text'])
feature_names = vectorizer.get_feature_names_out()
matrix = vectors.todense()

tfidf_df = pd.DataFrame(matrix, columns = feature_names)

tfidf_df

00  000  0000  00000  000000  0000000  00000001  0000029  00001  \
0     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
1     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
2     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
4     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
...   ...  ...   ...    ...     ...      ...       ...      ...    ...   
3477  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3478  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3479  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3480  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3481  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   

      0000110  ...  éti  éva  éverienn  évidents  évlzed28  éwopart   éx  \
0         0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
1         0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
2         0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
3         0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
4         0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
...       ...  ...  ...  ...       ...       ...       ...      ...  ...   
3477      0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
3478      0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
3479      0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
3480      0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   
3481      0.0  ...  0.0  0.0       0.0       0.0       0.0      0.0  0.0   

      éxcépt  éxet   éy  
0        0.0   0.0  0.0  
1        0.0   0.0  0.0  
2        0.0   0.0  0.0  
3        0.0   0.0  0.0  
4        0.0   0.0  0.0  
...      ...   ...  ...  
3477     0.0   0.0  0.0  
3478     0.0   0.0  0.0  
3479     0.0   0.0  0.0  
3480     0.0   0.0  0.0  
3481     0.0   0.0  0.0  

[3482 rows x 77650 columns]

In [12]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
tfidf_df['data_label']= le.fit_transform(df['our_label'])



In [13]:
tfidf_df

00  000  0000  00000  000000  0000000  00000001  0000029  00001  \
0     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
1     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
2     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
4     0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
...   ...  ...   ...    ...     ...      ...       ...      ...    ...   
3477  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3478  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3479  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3480  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   
3481  0.0  0.0   0.0    0.0     0.0      0.0       0.0      0.0    0.0   

      0000110  ...  éva  éverienn  évidents  évlzed28  éwopart   éx  éxcépt  \
0         0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
1         0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
2         0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
3         0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
4         0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
...       ...  ...  ...       ...       ...       ...      ...  ...     ...   
3477      0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
3478      0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
3479      0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
3480      0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   
3481      0.0  ...  0.0       0.0       0.0       0.0      0.0  0.0     0.0   

      éxet   éy  data_label  
0      0.0  0.0           9  
1      0.0  0.0           9  
2      0.0  0.0           9  
3      0.0  0.0           9  
4      0.0  0.0           9  
...    ...  ...         ...  
3477   0.0  0.0           0  
3478   0.0  0.0           0  
3479   0.0  0.0           0  
3480   0.0  0.0           0  
3481   0.0  0.0           0  

[3482 rows x 77651 columns]

In [14]:
X =tfidf_df.iloc[:,:-1]
y =tfidf_df['data_label']

print(X.shape)
print(y.shape)

(3482, 77650)
(3482,)


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =10)

# RandomForest Classifier

In [17]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)

In [18]:
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [20]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7712918660287081


In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 40,   2,   3,   4,   4,   0,  20,   0,   0,   0],
       [  0, 178,   0,   1,   2,   0,   0,   0,   0,   0],
       [  2,   4,  96,   6,   3,   0,  10,   0,   0,   0],
       [  1,   3,   2, 115,  31,   1,   2,   1,   0,   0],
       [  0,   6,   0,  13, 185,   0,   1,   2,   0,   0],
       [  2,   0,   1,   3,   2,  39,   2,   2,   0,   0],
       [  1,   1,   2,   0,   0,   0,  57,   0,   0,   0],
       [  4,   3,   2,  26,   8,   0,   1,  13,   1,   7],
       [  0,   0,   2,   3,   0,   0,   0,   0,  37,   0],
       [  4,   0,  12,   8,   4,   1,   3,  10,   0,  46]])

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.55      0.63        73
           1       0.90      0.98      0.94       181
           2       0.80      0.79      0.80       121
           3       0.64      0.74      0.69       156
           4       0.77      0.89      0.83       207
           5       0.95      0.76      0.85        51
           6       0.59      0.93      0.73        61
           7       0.46      0.20      0.28        65
           8       0.97      0.88      0.93        42
           9       0.87      0.52      0.65        88

    accuracy                           0.77      1045
   macro avg       0.77      0.73      0.73      1045
weighted avg       0.77      0.77      0.76      1045



# KNN classifier

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

Accuracy: 0.06889952153110047
[[  6   0   0   0   0   0  67   0   0   0]
 [ 11   0   0   0   0   0 170   0   0   0]
 [  6   0   2   0   0   0 113   0   0   0]
 [  7   0   0   2   0   0 147   0   0   0]
 [  9   0   0   0   2   0 196   0   0   0]
 [  1   0   0   0   0   0  50   0   0   0]
 [  1   0   0   0   0   0  60   0   0   0]
 [  1   0   0   0   0   0  64   0   0   0]
 [  3   0   0   0   0   0  39   0   0   0]
 [  6   0   0   0   0   0  82   0   0   0]]
              precision    recall  f1-score   support

           0       0.12      0.08      0.10        73
           1       0.00      0.00      0.00       181
           2       1.00      0.02      0.03       121
           3       1.00      0.01      0.03       156
           4       1.00      0.01      0.02       207
           5       0.00      0.00      0.00        51
           6       0.06      0.98      0.11        61
           7       0.00      0.00      0.00        65
           8       0.00      0.00      0.00        4

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
for i in range(1,15):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.11961722488038277
Accuracy: 0.0861244019138756
Accuracy: 0.08325358851674641
Accuracy: 0.0861244019138756
Accuracy: 0.08038277511961722
Accuracy: 0.07655502392344497
Accuracy: 0.06889952153110047
Accuracy: 0.06889952153110047
Accuracy: 0.06411483253588517
Accuracy: 0.06220095693779904
Accuracy: 0.06315789473684211
Accuracy: 0.06315789473684211
Accuracy: 0.06220095693779904
Accuracy: 0.06124401913875598


# SVM classifier 

In [16]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [17]:
y_pred = clf.predict(X_test)

In [18]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8172248803827751


In [19]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 44   0   4   2   3   0  19   1   0   0]
 [  0 175   1   2   2   1   0   0   0   0]
 [  0   0 108   2   3   2   3   1   0   2]
 [  0   1   2 124  15   1   1   9   0   3]
 [  0   1   2  13 182   2   0   4   0   3]
 [  0   0   0   2   1  42   2   4   0   0]
 [  0   1   4   2   4   0  50   0   0   0]
 [  0   0   3  17   5   1   0  33   1   5]
 [  0   0   0   2   0   0   1   0  38   1]
 [  0   0   8   7   2   0   3  10   0  58]]
              precision    recall  f1-score   support

           0       1.00      0.60      0.75        73
           1       0.98      0.97      0.97       181
           2       0.82      0.89      0.85       121
           3       0.72      0.79      0.75       156
           4       0.84      0.88      0.86       207
           5       0.86      0.82      0.84        51
           6       0.63      0.82      0.71        61
           7       0.53      0.51      0.52        65
           8       0.97      0.90      0.94        42
           9       0.81     